name: viser
description: "Sistema de Reconocimiento Facial VISER - Control de Acceso."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0

  # Módulo 2: Reconocimiento Facial
  camera: ^0.11.1
  image: 4.1.5
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1

  # Módulo 3: Base de Datos y Sincronización
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.9.0
  path_provider: ^2.0.11
  image_picker: ^1.0.7
  uuid: ^4.5.1

  # Íconos y Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hoja.png
    - assets/logo.png
    - assets/logoviser.png
    - assets/mobilefacenet.tflite

# ================================
# 🚀 ÍCONO DE LA APP
# ================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logoviser.png"
  remove_alpha_ios: true

# ================================
# ⚡ PANTALLA DE CARGA ANIMADA (SPLASH)
# ================================
flutter_native_splash:
  color: "#f24e4e"
  image: assets/hoja.png
  branding_mode: bottom
  branding: assets/hoja.png
  android_12:
    image: assets/hoja.png
    color: "#f24e4e"
  web: false
